// This file is auto-generated by prisma-typed-json-generator

export type Address = {
  street: string;
  city: string;
  country: string;
}

export type OperatingHours = {
  dayOfWeek: number;
  openTime: string;
  closeTime: string;
}

