function extractJsonTypeAnnotations(schemaContent: string): Record<string, string> {
	const result: Record<string, string> = {};
	const modelRegex = /model\s+([A-Za-z0-9_]+)\s*\{([\s\S]*?)\}/g;
	let modelMatch;
	while ((modelMatch = modelRegex.exec(schemaContent)) !== null) {
		const modelName = modelMatch[1];
		const body = modelMatch[2];
		for (const line of body.split('\n')) {
			const fieldMatch = /^\s*([A-Za-z0-9_]+)\s+Json.*@type\(([^)]+)\)/.exec(line);
			if (fieldMatch) {
				const fieldName = fieldMatch[1];
				const typeName = fieldMatch[2];
				result[`${modelName}.${fieldName}`] = typeName;
			}
		}
	}
	return result;
}
import generatorHelper, { GeneratorOptions } from '@prisma/generator-helper';
import internals from '@prisma/internals'
import path from 'path'
import pkg from '../package.json' with { type: "json" }
import fs from 'fs'


export function extractCommentedTypes(schemaContent: string): Record<string, Record<string, string>> {
	const commentedTypeBlocks: string[] = [];
	const typeBlockRegex = /\/\/\s*type\s+([A-Za-z0-9_]+)\s*\{([\s\S]*?)\}/g;
	let match;
	while ((match = typeBlockRegex.exec(schemaContent)) !== null) {
		commentedTypeBlocks.push(match[0]);
	}
	const typeObjects: Record<string, Record<string, string>> = {};
	for (const block of commentedTypeBlocks) {
		const headerMatch = /type\s+([A-Za-z0-9_]+)\s*\{([\s\S]*?)\}/.exec(block);
		if (!headerMatch) continue;
		const typeName = headerMatch[1];
		const body = headerMatch[2];
		const fields: Record<string, string> = {};
		for (const line of body.split('\n')) {
			const cleaned = line.replace(/^\s*\/\//, '').trim();
			if (!cleaned) continue;
			const fieldMatch = /^([A-Za-z0-9_]+)\s+([A-Za-z0-9_\[\]?]+)$/.exec(cleaned);
			if (fieldMatch) {
				fields[fieldMatch[1]] = fieldMatch[2];
			}
		}
		typeObjects[typeName] = fields;
	}
	return typeObjects;
}

export async function writeTypesFile(
	typeObjects: Record<string, Record<string, string>>,
	clientDir: string
) {
	let typeFileContent = '// This file is auto-generated by @innovixx/prisma-typed-json-generator\n\n';
	for (const [typeName, fields] of Object.entries(typeObjects)) {
		typeFileContent += `export type ${typeName} = {\n`;
		for (const [field, type] of Object.entries(fields)) {
			let tsType = type
				.replace(/^string$/i, 'string')
				.replace(/^int$/i, 'number')
				.replace(/^float$/i, 'number')
				.replace(/^boolean$/i, 'boolean')
				.replace(/^json$/i, 'any')
				.replace(/\?$/, ' | null')
				.replace(/\[\]$/, '[]');
			typeFileContent += `  ${field}: ${tsType};\n`;
		}
		typeFileContent += '}\n\n';
	}
	const outputPath = path.join(clientDir, 'prisma-json.types.d.ts');
	await fs.promises.mkdir(clientDir, { recursive: true });
	await fs.promises.writeFile(outputPath, typeFileContent, 'utf-8');
	return outputPath;
}

const { generatorHandler } = generatorHelper;
const { logger } = internals;

generatorHandler({
	onManifest() {
		return {
			version: pkg.version,
			defaultOutput: '../generated',
			prettyName: "prisma-typed-json-generator",
		}
	},
	onGenerate: async (options: GeneratorOptions) => {
		logger.info(`prisma-typed-json-generator:Generating...`)

		const schemaFileLocation = options.generator.sourceFilePath

		const clientGenerator = options.otherGenerators.find((g) => g.name === 'client')
		if (!clientGenerator) throw new Error('Prisma Client generator not found. Please ensure that generator Client is specified in your schema.');

		const clientOutput = clientGenerator.output?.value

		const schemaContent = await fs.promises.readFile(schemaFileLocation, 'utf-8');
		const typeObjects = extractCommentedTypes(schemaContent);

		if (clientOutput) {
			await writeTypesFile(typeObjects, clientOutput);
		}

		if (clientOutput) {
			const indexDtsPath = path.join(clientOutput, 'index.d.ts');
			let indexDtsContent = await fs.promises.readFile(indexDtsPath, 'utf-8');
			let updated = false;

			const jsonTypeAnnotations = extractJsonTypeAnnotations(schemaContent);
			for (const [modelField, typeName] of Object.entries(jsonTypeAnnotations)) {
				const [model, field] = modelField.split('.');
				const payloadBlockRegex = new RegExp(`export type \\$${model}Payload<[^=]+=[^>]+> = \\{([\\s\\S]*?)\\n\\}`, 'g');
				indexDtsContent = indexDtsContent.replace(payloadBlockRegex, (block) => {
					const lines = block.split('\n');
					let inScalars = false;
					for (let i = 0; i < lines.length; i++) {
						if (lines[i].includes('scalars: $Extensions.GetPayloadResult<{')) inScalars = true;
						if (inScalars && lines[i].includes(`${field}: Prisma.JsonValue`)) {
							lines[i] = lines[i].replace('Prisma.JsonValue', `PrismaJsonTypes.${typeName}`);
							updated = true;
						}
						if (inScalars && lines[i].includes('}, ExtArgs["result"]')) inScalars = false;
					}
					return lines.join('\n');
				});
			}
			if (updated) {
				const importLine = `import * as PrismaJsonTypes from './prisma-json.types';`;
				if (!indexDtsContent.includes(importLine)) {
					indexDtsContent = indexDtsContent.replace(/(import .*?;\n)/, `$1${importLine}\n`);
				}
				await fs.promises.writeFile(indexDtsPath, indexDtsContent, 'utf-8');
			}
		}

		logger.info(`prisma-typed-json-generator:Generating...Done`)
	},
})
